api:
  dashboard: true

providers:
  file:
    directory: "configs"
    watch: true

entryPoints:
  websecure:
    address: ":443"
    reusePort: true
    http:
      tls: true

  web:
    address: ":80"
    reusePort: true
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
          priority: 100

certificatesResolvers:
  letsencrypt:
    acme:
      email: your@email.com
      storage: acme.json
      httpChallenge:
        entryPoint: web