http:
  routers:
    myweb:
      rule: "(Host(`site.local`) || Host(`www.site.local`)) && PathPrefix(`/`)"
      service: "goweb"
      tls:
        certResolver: letsencrypt
        domains:
          - main: "site.local"
            sans:
              - "www.site.local"

    mysubweb:
      rule: "Host(`mysub.site.local`) && PathPrefix(`/`)"
      service: "goweb"
      tls:
        certResolver: letsencrypt
 letsencrypt

  services:
    goweb:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8100"
